application: saskdance
version: dev
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  mime_type: image/vnd.microsoft.icon
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /static/*
  static_dir: static

- url: /.*
  script: app.main.application

libraries:
- name: jinja2
  version: latest
- name: webapp2
  version: latest